### ISSUE TITLE
Bug with numpy==1.26.2

### ISSUE THREAD

**Issue by juanmalagon** [NibuTake/PyDEA#15]
### Type

New

### Description

Just running

`import numpy as np`
`from Pyfrontier.frontier_model import EnvelopeDEA`

returns

`ValueError: mutable default <class 'numpy.ndarray'> for field _weights is not allowed: use default_factory`

### Environment

Python 3.11.3

numpy==1.26.2
pandas==2.1.4

**Comment by NibuTake** [comment]
@juanmalagon 
Thank you for reporting the bug!
Sorry for the delay in confirming. I will fix it immediately to make it compatible with Python 3.11.
